import { date } from 'quasar'

export const voucherColumns = [
  {
    name: 'id',
    required: true,
    label: 'ID',
    align: 'left',
    field: 'id',
    display: { visible: true, index: 1 },
    sortable: true,
    sort: { order: '1', index: 1 },
  },
  {
    name: 'voucher_type_name',
    required: true,
    label: 'Voucher Type',
    align: 'left',
    field: 'voucher_type_name',
    sortable: true,
    display: { visible: true, index: 2 },
    sort: { order: '1', index: 0 },
  },
  {
    name: 'voucher_date',
    required: true,
    label: 'Date',
    align: 'left',
    field: 'voucher_date',
    format: (val) => date.formatDate(new Date(val), 'DD-MM-YYYY'),
    sortable: true,
    display: { visible: true, index: 2 },
    sort: { order: '1', index: 0 },
  },
  {
    name: 'voucher_no',
    required: true,
    label: 'Voucher No',
    align: 'left',
    field: 'voucher_no',
    sortable: true,
    display: { visible: true, index: 2 },
    sort: { order: '1', index: 0 },
  },
]

export const voucherProductColumns = [
  {
    name: 'id',
    required: true,
    label: 'ID',
    align: 'left',
    field: 'id',
    display: { visible: true, index: 1 },
    sortable: true,
    sort: { order: '1', index: 1 },
  },
  {
    name: 'product_name',
    required: true,
    label: 'Product Name',
    align: 'left',
    field: 'product_name',
    sortable: true,
    display: { visible: true, index: 2 },
    sort: { order: '1', index: 0 },
  },
  {
    name: 'unit_name',
    required: true,
    label: 'Unit Name',
    align: 'left',
    field: 'unit_name',
    sortable: true,
    display: { visible: true, index: 2 },
    sort: { order: '1', index: 0 },
  },
  {
    name: 'quantity',
    required: true,
    label: 'Quantity',
    align: 'left',
    field: 'quantity',
    sortable: true,
    display: { visible: true, index: 2 },
    sort: { order: '1', index: 0 },
  },
  {
    name: 'rate',
    required: true,
    label: 'rate',
    align: 'left',
    field: 'rate',
    sortable: true,
    display: { visible: true, index: 2 },
    sort: { order: '1', index: 0 },
  },
  {
    name: 'amount',
    required: true,
    label: 'Amount',
    align: 'left',
    field: 'amount',
    sortable: true,
    display: { visible: true, index: 2 },
    sort: { order: '1', index: 0 },
  },
]
